---
- name: Create database for PDA
  mysql_db:
    name: pda
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present

- name: Add user for PDA
  mysql_user:
    name: pda
    password: "{{ pda_db_password }}"
    priv: 'pda.*:ALL'
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
