---
- name: Create daemon
  template:
    src: daemon.j2
    dest: /etc/frr/daemon

- name: Create frr.conf from template if it doesn't exist already.
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    force: no