---
- name: Configure the Frrouting APT key
  apt_key:
    url: https://deb.frrouting.org/frr/keys.asc

- name: Add Frrouting repository
  apt_repository:
    repo: 'deb https://deb.frrouting.org/frr bionic frr-stable'
    state: present
    update_cache: yes

- name: Install Frrouting
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - frr
    - frr-pythontools