---
- name: Create subnet4.json
  when: ipv4_server
  template:
    src: subnet4.json.j2
    dest: /etc/kea/subnet4.json
    force: false

- name: Create subnet6.json
  when: ipv6_server
  template:
    src: subnet6.json.j2
    dest: /etc/kea/subnet6.json
    force: false

- name: Create forward-ddns.json
  when: ddns_server
  template:
    src: forward-ddns.json.j2
    dest: /etc/kea/forward-ddns.json
    force: false

- name: Create reverse-ddns.json
  when: ddns_server
  template:
    src: reverse-ddns.json.j2
    dest: /etc/kea/reverse-ddns.json
    force: false

- name: Template kea-dhcp4.conf
  when: ipv4_server
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
  notify: dhcp4_restart

- name: Template kea-dhcp6.conf
  when: ipv6_server
  template:
    src: kea-dhcp6.conf.j2
    dest: /etc/kea/kea-dhcp6.conf
  notify: dhcp6_restart

- name: Template kea-dhcp-ddns.conf
  when: ddns_server
  template:
    src: kea-dhcp-ddns.conf.j2
    dest: /etc/kea/kea-dhcp-ddns.conf
  notify: kea_ddns_restart
