---
- name: Install MariaDB
  apt:
    name: mariadb-server
    update_cache: yes
    state: present

- name: Install python-pymysql
  apt:
    name: python-pymysql
    update_cache: yes
    state: present