---
- hosts: all
  roles:
    - netplan
    - frr
  vars_files:
    - variables.yml

- hosts: all
  roles:
  - { role: PowerDNS.pdns_recursor,
    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_42 }}" }
  vars_files:
    - variables.yml